version: '3.1'
services:
  api:
    build: .
    volumes:
      - .:/src
    ports:
      - 3000:3000
      - 9230:9230
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: 123456
      DATABASE: postgres
      DB_DRIVER: postgres
      NODE_ENV: development
    command: npm run dev
    networks:
      - app_net
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net
networks:
  app_net:
volumes:
  pg-data:
